name: dart_stringprep
version: 0.1.0+1-dev
author: "Ronit Ramdam BK <ron.ram5126@gmail.com>"
homepage: https://github.com/ronram5126/stun-dart
description: Implementation of String prep function for dart. This source was created using Arachnid's stringprep-js. It is suppose to be implementation of RFC3454

environment:
  sdk: ">=2.2.2"

dependencies:
  
dev_dependencies:
  test: ^1.3.0